// 現段階ではJavaScriptを必要とする機能はありません。
// 将来の機能追加用にファイルのみ配置しています。
document.addEventListener('DOMContentLoaded',()=>{const slides=document.querySelectorAll('.about-slideshow img');if(slides.length<2)return;let current=0;setInterval(()=>{slides[current].classList.remove('is-active');current=(current+1)%slides.length;slides[current].classList.add('is-active')},10000)});
document.addEventListener('DOMContentLoaded',()=>{const sections=[...document.querySelectorAll('main > .section, main .content-section')];if(!sections.length)return;document.body.classList.add('reveal-ready');if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){sections.forEach(section=>section.classList.add('is-visible'));return}const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}})},{threshold:.12,rootMargin:'0px 0px -8%'});sections.forEach(section=>observer.observe(section))});
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.header-inner').forEach(header=>{const nav=header.querySelector('.global-nav');if(!nav)return;const button=document.createElement('button');button.className='menu-toggle';button.type='button';button.setAttribute('aria-label','メニューを開く');button.setAttribute('aria-expanded','false');button.textContent='☰';header.appendChild(button);button.addEventListener('click',()=>{const open=nav.classList.toggle('is-open');button.setAttribute('aria-expanded',String(open));button.textContent=open?'×':'☰'})})});
const formatNewsDate=date=>date.replaceAll('-','.');
const newsLink=id=>`information/index.html#${encodeURIComponent(id)}`;
const createNewsItem=news=>{const item=document.createElement('article');item.className='news-item';const time=document.createElement('time');time.dateTime=news.date;time.textContent=formatNewsDate(news.date);const link=document.createElement('a');link.href=newsLink(news.id);link.textContent=news.title;const tag=document.createElement('span');tag.className='tag';tag.textContent=news.tag;item.append(time,link,tag);return item};
const createNewsDetail=news=>{const item=document.createElement('article');item.className='info-row';item.id=news.id;const time=document.createElement('time');time.dateTime=news.date;time.textContent=formatNewsDate(news.date);const content=document.createElement('div');const title=document.createElement('h3');title.textContent=news.title;content.append(title);news.body.forEach(text=>{const paragraph=document.createElement('p');paragraph.textContent=text;content.append(paragraph)});item.append(time,content);return item};
document.addEventListener('DOMContentLoaded',async()=>{const source=document.querySelector('[data-news-source]');if(!source)return;try{const response=await fetch(source.dataset.newsSource,{cache:'no-cache'});if(!response.ok)throw new Error('News data could not be loaded');const news=await response.json();if(!Array.isArray(news))throw new Error('News data is invalid');const sorted=[...news].sort((a,b)=>b.date.localeCompare(a.date));const topList=document.querySelector('#top-news-list');if(topList){topList.replaceChildren(...sorted.slice(0,5).map(createNewsItem))}const detailList=document.querySelector('#information-news-list');if(detailList){detailList.replaceChildren(...sorted.map(createNewsDetail));detailList.hidden=false;detailList.previousElementSibling.hidden=true}}catch(error){console.error(error)}});
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.faq-item').forEach((item,index)=>{const question=item.querySelector('.faq-q');const answer=item.querySelector('.faq-a');if(!question||!answer)return;const answerId=`faq-answer-${index+1}`;question.setAttribute('role','button');question.setAttribute('tabindex','0');question.setAttribute('aria-expanded','false');question.setAttribute('aria-controls',answerId);answer.id=answerId;const toggle=()=>{const open=item.classList.toggle('is-open');question.setAttribute('aria-expanded',String(open))};question.addEventListener('click',toggle);question.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();toggle()}})})});
document.addEventListener('DOMContentLoaded',()=>{const staffCard=' .about-staff .staff-card';document.addEventListener('mouseenter',event=>{if(event.target.closest(staffCard))event.stopImmediatePropagation()},true);document.addEventListener('mouseleave',event=>{if(event.target.closest(staffCard))event.stopImmediatePropagation()},true)});
document.addEventListener('DOMContentLoaded',()=>{const closeButton=document.querySelector('.staff-modal-close');if(closeButton){closeButton.textContent='× 閉じる';closeButton.setAttribute('aria-label','閉じる')}});
document.addEventListener('DOMContentLoaded',()=>{const observer=new MutationObserver(()=>{const closeButton=document.querySelector('.staff-modal-close');if(closeButton){closeButton.textContent='× 閉じる';closeButton.setAttribute('aria-label','閉じる');observer.disconnect()}});observer.observe(document.body,{childList:true});});
document.addEventListener('DOMContentLoaded',()=>{const cards=[...document.querySelectorAll('.about-staff .staff-card')];if(!cards.length)return;const modal=document.createElement('div');modal.className='staff-modal';modal.hidden=true;modal.innerHTML='<div class="staff-modal-dialog" role="dialog" aria-modal="true" aria-labelledby="staff-modal-name" tabindex="-1"><button class="staff-modal-close" type="button" aria-label="閉じる">×</button><div class="staff-modal-body"></div></div>';document.body.append(modal);const dialog=modal.querySelector('.staff-modal-dialog'),body=modal.querySelector('.staff-modal-body'),closeButton=modal.querySelector('.staff-modal-close');let hoverTimer;let lastFocused;const close=()=>{clearTimeout(hoverTimer);modal.classList.remove('is-hover');modal.hidden=true;if(lastFocused)lastFocused.focus()};const show=(card,persistent=false)=>{clearTimeout(hoverTimer);lastFocused=card;modal.classList.toggle('is-hover',!persistent);body.replaceChildren();const sourceImage=card.querySelector('img');const image=sourceImage.cloneNode(true);image.style.objectPosition=getComputedStyle(sourceImage).objectPosition;const content=document.createElement('div');const role=card.querySelector('.role').cloneNode(true);const name=document.createElement('h2');name.id='staff-modal-name';name.textContent=card.querySelector('h3').textContent;content.append(role,name,...[...card.querySelectorAll('p:not(.role)')].map(item=>item.cloneNode(true)));body.append(image,content);modal.hidden=false;if(persistent)dialog.focus()};cards.forEach(card=>{card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-haspopup','dialog');card.addEventListener('mouseenter',()=>{if(matchMedia('(hover:hover)').matches)show(card)});card.addEventListener('mouseleave',()=>{if(matchMedia('(hover:hover)').matches)hoverTimer=setTimeout(close,250)});card.addEventListener('click',()=>show(card,true));card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();show(card,true)}})});closeButton.addEventListener('click',close);modal.addEventListener('click',event=>{if(event.target===modal)close()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!modal.hidden)close()})});
